version: '2'

services: 
    #api.gestionin.com
    backend:
        build: ./backend/
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend/:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    #gestionin.com
    frontend:
        build: ./frontend

    db:
        image: postgres:9.6.19-alpine
        environment: 
            POSTGRES_DB: ${postres_db}
            POSTGRES_USER: ${postgres_user}
            POSTGRES_PASSWORD: ${postgres_password}
        ports:
            - 8001:8001
        labels:
            - "traefik.enable=true"

        

    traefik:
        image: traefik:v2.3.1
        container_name: "traefik"
        command:
            - "--api.insecure=true" 
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"   
        ports: 
            - 8080:8080
            - 80:80
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    