version: '2'

services: 
    # api.gestionin.com
    backend:
        build: 
            context: .
            dockerfile: ./compose/local/backend/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./.envs/.local/.postgres
            - ./.envs/.local/.django
        volumes:
            - ./backend/:/code
        ports:
            - 8000:8000
        depends_on:
            - db




    # #gestionin.com
    # frontend:
    #     build: ./frontend




    db:
        image: postgres:9.6.19-alpine
#        build:
#            context: .
#            dockerfile: ./compose/local/db/Dockerfile
        env_file:
            - ./.envs/.local/.postgres
        ports: 
            - 5432:5432
        volumes:
            - ./db/:/var/lib/postgresql/data
        # labels:
        #     - "traefik.enable=true"

        

    # traefik:
    #     image: traefik:v2.3.1
    #     container_name: "traefik"
    #     command:
    #         - "--api.insecure=true" 
    #         - "--providers.docker=true"
    #         - "--providers.docker.exposedbydefault=false"
    #         - "--entrypoints.web.address=:80"   
    #     ports: 
    #         - 8080:8080
    #         - 80:80
    #     volumes: 
    #         - "/var/run/docker.sock:/var/run/docker.sock:ro"
    