# Generated by Django 2.2 on 2020-10-29 19:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando fue modificado por ultima vez', verbose_name='modified at')),
                ('rol', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando fue modificado por ultima vez', verbose_name='modified at')),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Rol')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando fue modificado por ultima vez', verbose_name='modified at')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El numero tiene que estar en el formato', regex='\\+?1?\\d{9,15}$')])),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='users.User')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
