# Generated by Django 2.2 on 2020-10-29 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franco',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, help_text='Cuando fue modificado por ultima vez', verbose_name='modified at')),
                ('dia', models.DateField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'unique_together': {('user', 'dia')},
            },
        ),
    ]
