# Generated by Django 2.2 on 2020-10-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_franco'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='auth_lvl',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
