# Generated by Django 2.2 on 2020-11-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_auto_20201101_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleusuario',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='core.Team'),
        ),
    ]
