# Generated by Django 2.2 on 2020-11-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_detalleusuario_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleUsuario',
            new_name='UserDetails',
        ),
    ]
