# Generated by Django 2.2 on 2020-11-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0007_auto_20201105_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='core.Team'),
        ),
    ]
