# Generated by Django 2.2 on 2020-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug_name',
            field=models.CharField(default='null', max_length=30, unique=True),
        ),
    ]
